group:
  - repos: |
      ardubev16/carpoolerbot
      ardubev16/lmbatbot
      ardubev16/punbot
    files:
      - source: sync-config
        deleteOrphaned: true
      - .dockerignore
      - .editorconfig
      - .gitignore
      - .pre-commit-config.yaml
      - .python-version
      - LICENSE
      - renovate.json

ardubev16/carpoolerbot:
  - source: Dockerfile.jinja
    dest: Dockerfile
    template:
      cmd: carpoolerbot

ardubev16/lmbatbot:
  - source: Dockerfile.jinja
    dest: Dockerfile
    template:
      cmd: lmbatbot
      instructions:
        post_build:
          - COPY ./data ./data
