group:
  - repos: |
      ardubev16/carpoolerbot
      ardubev16/lmbatbot
      ardubev16/punbot
    files:
      - .dockerignore
      - .editorconfig
      - .gitignore
      - .pre-commit-config.yaml
      - LICENSE
      - pyproject.toml
      - renovate.json
