group:
  - repos: |
      ardubev16/carpoolerbot
      ardubev16/lmbatbot
      ardubev16/punbot
    files:
      - sync-config
      - .dockerignore
      - .editorconfig
      - .gitignore
      - .pre-commit-config.yaml
      - .python-version
      - LICENSE
      - renovate.json
