name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          GIT_USERNAME: Github Actions Bot
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          CONFIG_PATH: .github/sync.yaml
          ASSIGNEES: ardubev16
          COMMIT_PREFIX: "chore(sync):"
